name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }} # Página de despliegue

    steps:
      # 1. Clonar el repositorio
      - name: Clone repository
        uses: actions/checkout@v4

      # 2. Instalar dependencias
      - name: Install dependencies
        run: pnpm i

      # 3. Construir el proyecto
      - name: Build project
        run: pnpm run build

      # 4. Subir el artefacto para GitHub Pages
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # 5. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: github/pages-action@v2
        with:
          # Puedes ajustar la rama donde deseas desplegar. Aquí se usa `gh-pages`.
          branch: main
          folder: dist
